# Generated by Django 3.2.14 on 2022-08-13 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='main_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=255)),
                ('sub_heading', models.CharField(max_length=255)),
                ('main_problem', models.CharField(max_length=6500)),
                ('author_name', models.CharField(max_length=255)),
            ],
        ),
    ]
