# Generated by Django 3.2.14 on 2022-08-16 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counsellor', models.CharField(max_length=255)),
                ('relavent_score', models.IntegerField()),
                ('summary', models.CharField(max_length=2000)),
                ('reply', models.CharField(max_length=2000)),
                ('case_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.main_data')),
            ],
        ),
        migrations.CreateModel(
            name='keywords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=255)),
                ('case_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.main_data')),
            ],
        ),
        migrations.CreateModel(
            name='CompletedCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.main_data')),
            ],
        ),
    ]
